POST https://fsopen-backend-part3b.onrender.com/api/persons
content-type: application/json

{
    "name": "Aro Helas",
    "number": "387562-34983",
    "id": "58752"
}

###
GET https://fsopen-backend-part3b.onrender.com/api/persons
###
GET https://fsopen-backend-part3b.onrender.com/api/persons/1